name: Update niv

on:
  schedule:
    # every day at 8am UTC
    - cron: '0 8 * * *'

  # can manually trigger this workflow
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    # https://github.com/nmattia/niv/issues/280
    - run: GITHUB_PATH= nix-shell --run "niv update"
    - uses: cachix/cachix-action@v10
      with:
        name: nix-getting-started-template
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        #authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
    - run: nix-shell --run "pre-commit run -a"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.12.0
      with:
        commit-message: "[automation] update niv dependencies"
        title: "[automation] update niv dependencies"
        branch: "automation/update-niv-dependencies"
